name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Lint HTML
        run: |
          npm install -g htmlhint
          htmlhint index.html
      - name: Run JS Tests
        run: node tests/script.test.js